import type { Job } from "../types/models.types"

const jobBoard: Job[] = [
  // Entry Level (No Education)
  { title: 'Odd Jobs', base: 800, req: null, certReq: null, tReq: 1, odds: 1, cat: 'Entry' },
  { title: 'Fast Food Worker', base: 1100, req: null, certReq: 'Food and Beverage', tReq: 1, odds: 0.9, cat: 'Entry' },
  { title: 'Retail Associate', base: 1200, req: null, certReq: 'Sales', tReq: 2, odds: 0.85, cat: 'Entry' },
  { title: 'Dishwasher', base: 1050, req: null, certReq: 'Food and Beverage', tReq: 1, odds: 0.95, cat: 'Entry' },
  { title: 'Day Laborer', base: 1300, req: null, certReq: 'Construction Safety', tReq: 2, odds: 0.8, cat: 'Entry' },
  { title: 'Warehouse Crew', base: 1500, req: 'HS Diploma', certReq: 'Supply Chain', tReq: 2, odds: 0.8, cat: 'Entry' },
  { title: 'Gig Delivery', base: 1250, req: null, certReq: 'Commercial Drivers License', tReq: 4, odds: 0.95, cat: 'Entry' },
  { title: 'Security Guard', base: 1400, req: 'HS Diploma', certReq: 'Construction Safety', tReq: 2, odds: 0.75, cat: 'Entry' },
  { title: 'Janitor', base: 1350, req: null, certReq: 'Construction Safety', tReq: 2, odds: 0.9, cat: 'Entry' },
  { title: 'Mail Sorter', base: 1550, req: 'HS Diploma', certReq: 'Customer Service', tReq: 2, odds: 0.7, cat: 'Entry' },
  { title: 'Office Admin', base: 2100, req: 'HS Diploma', certReq: 'Human Resources', tReq: 3, odds: 0.8, cat: 'Entry' },
  { title: 'Bank Teller', base: 1900, req: 'HS Diploma', certReq: 'Customer Service', tReq: 3, odds: 0.7, cat: 'Entry' },
  { title: 'Vet Assistant', base: 1850, req: 'HS Diploma', certReq: 'Medical Assist', tReq: 2, odds: 0.7, cat: 'Entry' },
  { title: 'Sales Rep', base: 4000, req: 'HS Diploma', certReq: 'Sales', tReq: 3, odds: 0.4, cat: 'Entry' },
  { title: 'Bartender', base: 2200, req: 'HS Diploma', certReq: 'Food and Beverage', tReq: 2, odds: 0.75, cat: 'Entry' },
  { title: 'Call Center Rep', base: 1800, req: 'HS Diploma', certReq: 'Customer Service', tReq: 2, odds: 0.8, cat: 'Entry' },
  { title: 'Grocery Stocker', base: 1600, req: 'HS Diploma', certReq: 'Customer Service', tReq: 1, odds: 0.9, cat: 'Entry' },
  { title: 'Laundry Attendant', base: 1200, req: 'HS Diploma', certReq: 'Customer Service', tReq: 1, odds: 0.85, cat: 'Entry' },

  // Military (Requires HS)
  { title: 'Army Private', base: 1900, req: 'HS Diploma', certReq: null, tReq: 1, odds: 0.95, cat: 'Military' },
  { title: 'Navy Seaman', base: 1950, req: 'HS Diploma', certReq: null, tReq: 1, odds: 0.9, cat: 'Military' },
  { title: 'Air Force Airman', base: 2000, req: 'HS Diploma', certReq: null, tReq: 1, odds: 0.85, cat: 'Military' },
  { title: 'Marine Corporal', base: 2100, req: 'HS Diploma', certReq: null, tReq: 1, odds: 0.8, cat: 'Military' },
  { title: 'Coast Guard Tech', base: 2050, req: 'HS Diploma', certReq: null, tReq: 1, odds: 0.8, cat: 'Military' },
  { title: 'Special Forces', base: 3500, req: 'HS Diploma', certReq: 'Six Sigma Black Belt', tReq: 5, odds: 0.005, cat: 'Military' },
  { title: 'Navy SEAL', base: 4000, req: 'Navy Seaman', certReq: 'Six Sigma Black Belt', tReq: 5, odds: 0.002, cat: 'Military' },
  { title: 'Air Force Pararescue', base: 3800, req: 'HS Diploma', certReq: null, tReq: 5, odds: 0.03, cat: 'Military' },
  { title: 'Marine Recon', base: 3600, req: 'HS Diploma', certReq: null, tReq: 5, odds: 0.04, cat: 'Military' },
  { title: 'Army Ranger', base: 3700, req: 'HS Diploma', certReq: null, tReq: 5, odds: 0.03, cat: 'Military' },
  { title: 'Coast Guard Rescue Swimmer', base: 3900, req: 'Coast Guard Tech', certReq: null, tReq: 5, odds: 0.02, cat: 'Military' },
  { title: 'Cybersecurity Specialist', base: 4500, req: 'HS Diploma', certReq: 'Cybersecurity', tReq: 4, odds: 0.1, cat: 'Military' },
  { title: 'Intelligence Analyst', base: 4300, req: 'HS Diploma', certReq: 'Intelligence Analyst', tReq: 4, odds: 0.15, cat: 'Military' },
  { title: 'Combat Medic', base: 4200, req: 'HS Diploma', certReq: 'Medical Assist', tReq: 4, odds: 0.2, cat: 'Military' },
  { title: 'Aviation Mechanic', base: 4100, req: 'HS Diploma', certReq: 'Aviation Maintenance Technician', tReq: 4, odds: 0.25, cat: 'Military' },
  { title: 'Logistics Specialist', base: 4000, req: 'HS Diploma', certReq: 'Supply Chain', tReq: 3, odds: 0.3, cat: 'Military' },
  { title: 'Public Affairs Specialist', base: 4300, req: 'HS Diploma', certReq: 'Public Relations', tReq: 4, odds: 0.1, cat: 'Military' },
  { title: 'Military Police', base: 3800, req: 'HS Diploma', certReq: 'Criminal Justice', tReq: 3, odds: 0.25, cat: 'Military' },
  { title: 'Field Artillery', base: 3600, req: 'HS Diploma', certReq: null, tReq: 3, odds: 0.35, cat: 'Military' },
  { title: 'Infantry', base: 3500, req: 'HS Diploma', certReq: null, tReq: 3, odds: 0.4, cat: 'Military' },

  // Skilled Trades (Trade Cert or specific certs)
  { title: 'Electrician', base: 2900, req: 'Trade Cert', certReq: 'OSHA 10/30 Safety Cards', tReq: 3, odds: 0.7, cat: 'Skilled' },
  { title: 'HVAC Tech', base: 2750, req: 'Trade Cert', certReq: 'HVAC', tReq: 3, odds: 0.75, cat: 'Skilled' },
  { title: 'Plumber', base: 3100, req: 'Trade Cert', certReq: 'Plumbing Design', tReq: 3, odds: 0.65, cat: 'Skilled' },
  { title: 'Welder', base: 3300, req: 'Trade Cert', certReq: 'Welder', tReq: 3, odds: 0.6, cat: 'Skilled' },
  { title: 'Dental Hygienist', base: 3500, req: 'Trade Cert', certReq: 'Sonographer', tReq: 3, odds: 0.55, cat: 'Skilled' },
  { title: 'Auto Mechanic', base: 2600, req: 'Trade Cert', certReq: 'Auto Service', tReq: 2, odds: 0.8, cat: 'Skilled' },
  { title: 'Truck Driver', base: 3800, req: 'Trade Cert', certReq: 'Commercial Drivers License', tReq: 3, odds: 0.85, cat: 'Skilled' },
  { title: 'Phlebotomist', base: 2400, req: 'Trade Cert', certReq: 'Medical Assist', tReq: 2, odds: 0.7, cat: 'Skilled' },
  { title: 'Paralegal', base: 2800, req: 'Trade Cert', certReq: 'Paralegal', tReq: 3, odds: 0.6, cat: 'Skilled' },
  { title: 'Cosmetologist', base: 2200, req: 'Trade Cert', certReq: 'Cosmetology Operator License', tReq: 3, odds: 0.8, cat: 'Skilled' },
  { title: 'Apprentice Mason', base: 1800, req: 'HS Diploma', certReq: 'Construction Safety', tReq: 3, odds: 0.8, cat: 'Skilled' },
  { title: 'CNC Operator', base: 2400, req: 'Trade Cert', certReq: 'Quality Control', tReq: 2, odds: 0.7, cat: 'Skilled' },
  { title: 'Landscape Lead', base: 2200, req: 'Trade Cert', certReq: 'Construction Safety', tReq: 3, odds: 0.9, cat: 'Skilled' },
  { title: 'Pharmacy Tech', base: 2000, req: 'Trade Cert', certReq: 'Pharmacy Technician', tReq: 3, odds: 0.75, cat: 'Skilled' },
  { title: 'Real Estate Agent', base: 3000, req: 'Trade Cert', certReq: 'Real Estate', tReq: 3, odds: 0.5, cat: 'Skilled' },
  { title: 'Chef de Partie', base: 3100, req: 'Trade Cert', certReq: 'Food and Beverage', tReq: 4, odds: 0.5, cat: 'Skilled' },
  { title: 'Firefighter', base: 4000, req: 'Trade Cert', certReq: 'Firefighter', tReq: 4, odds: 0.3, cat: 'Skilled' },
  { title: 'Electric Lineworker', base: 4500, req: 'Trade Cert', certReq: 'OSHA 10/30 Safety Cards', tReq: 4, odds: 0.25, cat: 'Skilled' },
  { title: 'Boilermaker', base: 4200, req: 'Trade Cert', certReq: 'Welding', tReq: 4, odds: 0.2, cat: 'Skilled' },
  { title: 'Glazier', base: 2800, req: 'Trade Cert', certReq: 'Construction Safety', tReq: 3, odds: 0.75, cat: 'Skilled' },
  { title: 'Roofer', base: 2600, req: 'Trade Cert', certReq: 'Construction Safety', tReq: 3, odds: 0.8, cat: 'Skilled' },
  { title: 'Ironworker', base: 3000, req: 'Trade Cert', certReq: 'Construction Safety', tReq: 4, odds: 0.7, cat: 'Skilled' },
  { title: 'Crane Operator', base: 4000, req: 'Trade Cert', certReq: 'Construction Safety', tReq: 4, odds: 0.6, cat: 'Skilled' },
  { title: 'Elevator Installer', base: 4500, req: 'Trade Cert', certReq: 'Construction Safety', tReq: 4, odds: 0.5, cat: 'Skilled' },
  { title: 'Pest Control Tech', base: 2500, req: 'Trade Cert', certReq: 'Pest Control', tReq: 3, odds: 0.7, cat: 'Skilled' },
  { title: 'Solar Panel Installer', base: 3500, req: 'Trade Cert', certReq: 'Construction Safety', tReq: 4, odds: 0.6, cat: 'Skilled' },
  { title: 'Wind Turbine Tech', base: 3800, req: 'Trade Cert', certReq: 'Construction Safety', tReq: 4, odds: 0.5, cat: 'Skilled' },
  { title: 'Heavy Equipment Operator', base: 3700, req: 'Trade Cert', certReq: 'Construction Safety', tReq: 4, odds: 0.55, cat: 'Skilled'},
  { title: 'Criminal Investigator', base: 4500, req: 'Trade Cert', certReq: 'Criminal Justice', tReq: 4, odds: 0.3, cat: 'Skilled' },
  { title: 'Forensic Analyst', base: 4300, req: 'Trade Cert', certReq: 'Forensic Science', tReq: 4, odds: 0.25, cat: 'Skilled' },
  { title: 'Correctional Officer', base: 3200, req: 'Trade Cert', certReq: 'Criminal Justice', tReq: 3, odds: 0.7, cat: 'Skilled' },
  { title: 'Court Clerk', base: 2800, req: 'Trade Cert', certReq: 'Paralegal', tReq: 3, odds: 0.6, cat: 'Skilled' },
  { title: 'Funeral Director', base: 4000, req: 'Trade Cert', certReq: 'Mortuary Science', tReq: 4, odds: 0.4, cat: 'Skilled' },
  { title: 'Massage Therapist', base: 2700, req: 'Trade Cert', certReq: 'Massage Therapy', tReq: 3, odds: 0.65, cat: 'Skilled' },
  { title: 'Physical Therapist Assistant', base: 3200, req: 'Trade Cert', certReq: 'Physical Therapy', tReq: 4, odds: 0.5, cat: 'Skilled' },
  { title: 'Occupational Therapy Assistant', base: 3100, req: 'Trade Cert', certReq: 'Occupational Therapy', tReq: 4, odds: 0.5, cat: 'Skilled' },
  { title: 'Veterinary Tech', base: 2900, req: 'Trade Cert', certReq: 'Veterinary Technician', tReq: 3, odds: 0.6, cat: 'Skilled' },
  { title: 'Radiologic Tech', base: 3600, req: 'Trade Cert', certReq: 'Radiologic Technology', tReq: 4, odds: 0.5, cat: 'Skilled' },
  { title: 'Respiratory Therapist', base: 3700, req: 'Trade Cert', certReq: 'Respiratory Therapy', tReq: 4, odds: 0.5, cat: 'Skilled' },
  { title: 'Dental Assistant', base: 2500, req: 'Trade Cert', certReq: 'Dental Assist', tReq: 2, odds: 0.7, cat: 'Skilled' },
  { title: 'Optician', base: 3000, req: 'Trade Cert', certReq: 'Optician', tReq: 3, odds: 0.6, cat: 'Skilled' },

  
  // Professional (Degree Required)
  { title: 'Software Dev', base: 6500, req: 'Bachelors Degree', certReq: 'Web Developer', tReq: 1, odds: 0.45, cat: 'Pro' },
  { title: 'Data Analyst', base: 5800, req: 'Bachelors Degree', certReq: 'Cloud Computing', tReq: 3, odds: 0.5, cat: 'Pro' },
  { title: 'Registered Nurse', base: 6000, req: 'Bachelors Degree', certReq: 'Medical Assist', tReq: 4, odds: 0.65, cat: 'Pro' },
  { title: 'Accountant', base: 5400, req: 'Bachelors Degree', certReq: 'Public Accountant', tReq: 4, odds: 0.55, cat: 'Pro' },
  { title: 'Civil Engineer', base: 6200, req: 'Bachelors Degree', certReq: 'Architectural Drafter', tReq: 4, odds: 0.4, cat: 'Pro' },
  { title: 'Graphic Designer', base: 4500, req: 'Bachelors Degree', certReq: 'Adobe Certified Professional', tReq: 1, odds: 0.6, cat: 'Pro' },
  { title: 'HR Specialist', base: 4900, req: 'Bachelors Degree', certReq: 'Human Resources', tReq: 4, odds: 0.55, cat: 'Pro' },
  { title: 'Marketing Coord.', base: 4700, req: 'Bachelors Degree', certReq: 'Sales', tReq: 4, odds: 0.5, cat: 'Pro' },
  { title: 'Lab Researcher', base: 5100, req: 'Bachelors Degree', certReq: 'Medical Laboratory Scientist', tReq: 4, odds: 0.4, cat: 'Pro' },
  { title: 'Social Worker', base: 4200, req: 'Bachelors Degree', certReq: 'Social Work Case Manager', tReq: 4, odds: 0.7, cat: 'Pro' },
  { title: 'IT Support', base: 3200, req: 'Trade Cert', certReq: 'Help Desk', tReq: 3, odds: 0.6, cat: 'Pro' },
  { title: 'Event Planner', base: 3400, req: 'Bachelors Degree', certReq: 'Project Management', tReq: 4, odds: 0.45, cat: 'Pro' },
  { title: 'Supply Chain Manager', base: 5600, req: 'Bachelors Degree', certReq: 'Supply Chain', tReq: 4, odds: 0.4, cat: 'Pro' },
  { title: 'Web Designer', base: 4200, req: 'Trade Cert', certReq: 'Web Developer', tReq: 1, odds: 0.55, cat: 'Pro' },
  { title: 'Publicist', base: 4800, req: 'Bachelors Degree', certReq: 'Sales', tReq: 4, odds: 0.35, cat: 'Pro' },
  { title: 'Physician', base: 15000, req: 'Medical School', certReq: 'Medical Billing', tReq: 4, odds: 0.8, cat: 'Pro' },
  { title: 'Surgeon', base: 18000, req: 'Medical School', certReq: null, tReq: 4, odds: 0.6, cat: 'Pro' },
  { title: 'Security Officer', base: 3500, req: 'HS Diploma', certReq: 'Cybersecurity', tReq: 3, odds: 0.7, cat: 'Pro' },
  { title: 'Court Reporter', base: 4500, req: 'Bachelors Degree', certReq: 'Court Reporter', tReq: 3, odds: 0.5, cat: 'Pro' },
  { title: 'Personal Trainer', base: 2800, req: 'HS Diploma', certReq: 'Personal Training', tReq: 4, odds: 0.75, cat: 'Pro' },
  { title: 'Pilot', base: 8000, req: 'Flight School', certReq: 'Commercial Pilot License', tReq: 4, odds: 0.3, cat: 'Pro' },
  { title: 'Air Traffic Controller', base: 9000, req: 'Bachelors Degree', certReq: 'Air Traffic Control', tReq: 4, odds: 0.25, cat: 'Pro' },
  { title: 'Financial Analyst', base: 7000, req: 'Bachelors Degree', certReq: 'Financial Analyst', tReq: 4, odds: 0.35, cat: 'Pro' },
  { title: 'Architect', base: 7500, req: 'Bachelors Degree', certReq: 'Architectural Drafter', tReq: 4, odds: 0.3, cat: 'Pro' },
  { title: 'University Professor', base: 6500, req: 'PhD', certReq: null, tReq: 4, odds: 0.2, cat: 'Pro' },
  { title: 'Research Scientist', base: 7200, req: 'PhD', certReq: null, tReq: 4, odds: 0.25, cat: 'Pro' },
  { title: 'Investment Banker', base: 12000, req: 'Bachelors Degree', certReq: 'Financial Analyst', tReq: 4, odds: 0.15, cat: 'Pro' },
  { title: 'Corporate Lawyer', base: 13000, req: 'Bachelors Degree', certReq: 'Paralegal', tReq: 4, odds: 0.1, cat: 'Pro' },
  { title: 'Airline Pilot', base: 8500, req: 'Flight School', certReq: 'Commercial Pilot License', tReq: 4, odds: 0.25, cat: 'Pro' },
  { title: 'Film Director', base: 11000, req: 'Bachelors Degree', certReq: 'Project Management', tReq: 4, odds: 0.05, cat: 'Pro' },
  { title: 'Lawyer', base: 9000, req: 'Law School', certReq: 'Paralegal', tReq: 4, odds: 0.2, cat: 'Pro' },
  { title: 'Professional Athlete', base: 15000, req: null, certReq: null, tReq: 5, odds: 0.01, cat: 'Pro' },
  { title: 'Tech Startup Founder', base: 20000, req: null, certReq: null, tReq: 5, odds: 0.02, cat: 'Pro' },
  { title: 'Billionaire CEO', base: 1000000, req: 'Ultra Wealthy Millionaire', certReq: 'Rotorcraft Category Rating', tReq: 5, odds: 0.0001, cat: 'Pro' },
  { title: 'Ultra Wealthy Millionaire', base: 5000000, req: 'Flight School', certReq: 'Rotorcraft Category Rating',  tReq: 5, odds: 0.001, cat: 'Pro' },
]

export default jobBoard
